# Generated by Django 2.0.7 on 2020-04-25 18:47

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('img', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='博文内容')),
                ('is_index', models.BooleanField(default=0, verbose_name='是否首页轮播')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '博文分类',
                'verbose_name_plural': '博文分类',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='市区')),
                ('city_id', models.CharField(max_length=12, verbose_name='市区编码')),
            ],
            options={
                'verbose_name': '市区',
                'verbose_name_plural': '市区',
            },
        ),
        migrations.CreateModel(
            name='GetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('message', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '留言处理',
                'verbose_name_plural': '留言处理',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='显示名称')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.City', verbose_name='地区')),
            ],
            options={
                'verbose_name': '博主信息',
                'verbose_name_plural': '博主信息',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='省份')),
                ('province_id', models.CharField(max_length=12, verbose_name='省份编码')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='articles',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Categories', verbose_name='所属类别'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='articles.Tags'),
        ),
    ]
