# Generated by Django 2.0.7 on 2020-04-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='province',
            name='province_id',
        ),
    ]
